### ISSUE TITLE
Error received from peer grpc_message: "missing or invalid authorization header"

### ISSUE THREAD

**Issue by jbemmel** [netboxlabs/diode#139]
Trying to follow the scenario here https://docs.netboxlabs.com/netbox-extensions/diode-agent/#create-a-discovery-configuration-file

The NAPALM connection works, but then the SDK connection to the Diode server fails. I'm guessing this may be a missing setting somewhere?

**Comment by jbemmel** [comment]
Full stacktrace:
```
Traceback (most recent call last):
  File "/home/jeroen/srlinux/netbox-diode/venv/lib/python3.12/site-packages/diode_napalm/cli/cli.py", line 96, in start_policy
    future.result()
  File "/usr/lib/python3.12/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/usr/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeroen/srlinux/netbox-diode/venv/lib/python3.12/site-packages/diode_napalm/cli/cli.py", line 77, in run_driver
    Client().ingest(info.hostname, data)
  File "/home/jeroen/srlinux/netbox-diode/venv/lib/python3.12/site-packages/diode_napalm/client.py", line 94, in ingest
    response = self.diode_client.ingest(translate_data(data))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeroen/srlinux/netbox-diode/venv/lib/python3.12/site-packages/netboxlabs/diode/sdk/client.py", line 211, in ingest
    raise DiodeClientError(err) from err
netboxlabs.diode.sdk.exceptions.DiodeClientError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "missing or invalid authorization header"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"missing or invalid authorization header", grpc_status:2, created_time:"2024-07-23T16:03:02.039367668+00:00"}"
>
ERROR:diode_napalm.cli.cli:Error while processing policy discovery_1: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "missing or invalid authorization header"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"missing or invalid authorization header", grpc_status:2, created_time:"2024-07-23T16:03:02.039367668+00:00"}"
>
```

**Comment by mfiedorowicz** [comment]
Hi @jbemmel, did you export `DIODE_API_KEY` or provide via .env file?

**Comment by jbemmel** [comment]
I was exporting it, but when I used `-e .env` it started working.

You may want to edit those instructions
